### ISSUE TITLE
Possibilité de renseigner plusieurs sources

### ISSUE THREAD

**Issue by jdesboeufs** [opencovid19-fr/data#168]
Même si la règle est un fichier YAML = 1 source, dans certains cas l'information d'une même source est éclatée sur plusieurs pages.

On pourrait accepter les tableaux pour le champ `source`.

Cf #158

**Comment by ColinMaudry** [comment]
Pour le CSV

- on créée autant de colonnes que de sources ?
- on sépare les URLs des sources multiples avec des `;`

**Comment by jdesboeufs** [comment]
On est pas obligé de tout mettre dans les CSV non ?
Dans les JSON oui.

**Comment by ColinMaudry** [comment]
Non effectivement, il n'y aura qu'à documenter que le CSV n'a que la source principale.

**Comment by Binnette** [comment]
Je propose tout simplement, la syntaxe suivante dans les yaml:

```yaml
source: # ou alors 'sources:' ?
 - nom: _______________ # source 1
   url: _______________
   archive: _______________
 - nom: _______________ # source 2
   url: _______________
   archive: _______________
```

Les `# source 1` et `# source 2` qui traînent permettent de référencer les sources:

```yaml
donneesNationales:
  casConfirmes: 5000 # d'après la source 1
  deces: 10 # d'après la source 2
```

Qu'en pensez vous ?
