### ISSUE TITLE
Incohérence depuis 18/03 pour les départements des Hauts de France

### ISSUE THREAD

**Issue by Florimondable** [opencovid19-fr/data#397]
Bonjour,

Visiblement il y a eu une remise à zéro pour le nombre de décès de chaque département des Hauts de France le 18 mars. Par exemple pour l’Oise on est passé le 17 mars de 34 décès à 6 le 18 mars.
Ou alors ils ressuscitent ? C’est bizarre.

**Comment by liszto** [comment]
Je ne vois pas d'incohérence de mon côté : 

Pour le 17 : 
```
  - nom: Oise
    code: DEP-60
    casConfirmes: 
    deces: 34
```

Pour le 18 : 
```
  - nom: Oise
    code: DEP-60 
    deces: 35
```

Les communiqués en archive sont bons également.

@Florimondable es-tu sûr ?
